<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AnimatedImage.Avalonia" Version="2.1.4" />
    <PackageReference Include="Avalonia" Version="12.1.2" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.2" />
    <PackageReference Include="Avalonia.Themes.Simple" Version="12.1.2" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
    <PackageReference Include="SteamKit2" Version="3.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\Main\LoginWindowView.axaml.cs">
      <DependentUpon>LoginWindowView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Main\HomeWindowView.axaml.cs">
      <DependentUpon>HomeWindowView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Main\GameLibraryViewModel.axaml.cs">
      <DependentUpon>GameLibraryViewModel.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\MainWindow.axaml.cs">
      <DependentUpon>MainWindow.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Secondary\GameView.axaml.cs">
      <DependentUpon>GameView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\AuxiliaryFriendView.axaml.cs">
      <DependentUpon>AuxiliaryFriendView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\AuxiliaryGameView.axaml.cs">
      <DependentUpon>AuxiliaryGameView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\AuxiliaryFriendView.axaml.cs">
      <DependentUpon>AuxiliaryFriendView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\AuxiliaryGameView.axaml.cs">
      <DependentUpon>AuxiliaryGameView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\LoadingView.axaml.cs">
      <DependentUpon>LoadingView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>
</Project>
