# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Building and Publishing

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish Windows x64
        run: dotnet publish -c Release -r win-x64

      - name: Publish Linux x64
        run: dotnet publish -c Release -r linux-x64
          
      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: InnoSetup.iss
          options: /O+

      - name: Upload Window artifacts
        uses: actions/upload-artifact@v7
        with:
          name: win-x64_package
          path: Output

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v7
        with:
          name: linux-x64_package
          path: bin/Release/net10.0/linux-x64/publish
          
          
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Linux package
        uses: actions/download-artifact@v8
        with:
          name: linux-x64_package
          path: linux-x64/
      
      - name: Fetch Windows package
        uses: actions/download-artifact@v8
        with:
          name: win-x64_package
          path: win-x64
          
      - run: ls linux-x64
      
      - name: Zip Linux archive
        run: zip -r linux-x64.zip linux-x64/
        
      - name: Zip Windows archive
        run: zip -r windows-x64.zip win-x64
        
      - name: Create a new release
        uses: softprops/action-gh-release@v3
        with: 
          body: |
            Testing this release automation
            through trial and error
          files: |
            windows-x64.zip
            linux-x64.zip



#  create-window-setup:
#    needs: build
#    runs-on: windows-latest
#    steps:
#      - name: Download Windows Package
#        uses: actions/download-artifact@v8
#        with:
#          name: win-x64_package
#          path: windows_build
#      - name: Download Inno Script
#        uses: actions/download-artifact@v8
#        with:
#          name: inno_script
#
#      - name: Compile .ISS to .EXE Installer
#        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
#        with:
#          path: InnoSetup.iss
#          options: /O+
#      - run: ls